test:
    path: /test/{height}/{width}
    defaults:
        _controller: 'AppBundle\Controller\TestController::loadAction'
        _scope: frontend
        _token_check: false
        height: 0
        width:  0
    requirements:
        height: '\d+'
        width:  '\d+'
        